spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.location=private/tomtemp
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

gameStation.uploads.location=C:/HOMEWARE/titreCDA/Game Station/ui/public/images

logging.pattern.console=
gameStation.logs.file=./logs/game-station-business
logging.file.name=${gameStation.logs.file}.current.log
logging.logback.rollingpolicy.file-name-pattern=${gameStation.logs.file}.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10KB
logging.logback.rollingpolicy.total-size-cap=100KB