spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.location=/var/readresolve.tech/ash/api/tmp
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

gameStation.uploads.location=/srv/readresolve.tech/ash/www/images

gameStation.ui.url=https://ash.readresolve.tech