DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE players (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	nickname VARCHAR(20) NOT NULL UNIQUE,
	password CHAR(60) NOT NULL,
	role_id INTEGER REFERENCES roles(id) NOT NULL,
    coins INTEGER
);

CREATE TABLE games (
	id SERIAL PRIMARY KEY,
	game_name VARCHAR(255) NOT NULL UNIQUE,
	game_detail VARCHAR(1000) NOT NULL UNIQUE,
	min_player INTEGER NOT NULL,
	max_player INTEGER NOT NULL,
	thumbnail VARCHAR(1000) NOT NULL UNIQUE,
	available BOOLEAN,
	victory_point INTEGER NOT NULL,
	lose_point INTEGER NOT NUll,
	draw_point INTEGER NOT Null
);

CREATE TABLE favorites (
	id SERIAL PRIMARY KEY,
	player_id INTEGER REFERENCES players(id) NOT NULL,
	game_id INTEGER REFERENCES games(id) NOT NULL,
	UNIQUE (player_id, game_id)
);