DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	nickname VARCHAR(20) NOT NULL UNIQUE,
	password CHAR(60) NOT NULL,
	role_id INTEGER REFERENCES roles(id) NOT NULL,
    coins INTEGER
);
